version: '3'
services:
  gui:
    build: ./gui
    ports:
      - "8080:8080"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ~/.aws/:/root/.aws:ro
    environment:
      - AWS_REGION=us-east-1
    ports:
      - "5000:5000"